services:
  db:
    image: postgres:16
    container_name: sbproj-db
    environment:
      POSTGRES_DB: sbproj
      POSTGRES_USER: sbproj_app
      POSTGRES_PASSWORD: sbproj_password
    ports:
      - "5432:5432"
    volumes:
      - sbproj_pgdata:/var/lib/postgresql/data

volumes:
  sbproj_pgdata: