# App name: [NOT YET FOUND]
spring.application.name=backend

# Postgres connection (eventually will run postgres through docker)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Flyway configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Automatic migration runs
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration